// @ts-nocheck
// GENERATED by FYNX API scripts/proof/sync-funded-policy.cjs. Do not edit.
'use strict';
import Decimal from 'decimal.js';
Decimal.set({precision:256,rounding:Decimal.ROUND_HALF_UP});
class InputError extends Error { constructor(message,code='invalid_input'){super(message);this.code=code;} }
const invalid=(s,c)=>{throw new InputError(s,c);};
function dec(v,name,positive=false){if(typeof v!=='string'||!/^[-+]?\d{1,18}(\.\d{1,12})?$/.test(v))invalid(`${name} must be a decimal string (up to 18 integer and 12 fractional digits).`);const d=new Decimal(v);if(positive&&!d.gt(0))invalid(`${name} must be positive.`);return d;}
const str=d=>d.toFixed();
const money=d=>d.toFixed(2);
function direction(d){if(!['long','short'].includes(d))invalid('direction must be long or short.');return d==='long'?1:-1;}
function risk(endpoint,x){
 let out;
 if(endpoint==='risk-reward'){
  const e=dec(x.entry_price,'entry_price',true),s=dec(x.stop_loss_price,'stop_loss_price',true),t=dec(x.take_profit_price,'take_profit_price',true),d=direction(x.direction);
  if(e.minus(s).mul(d).lte(0)||t.minus(e).mul(d).lte(0))invalid('Stop and target must be on the correct sides of entry.','invalid_direction_prices');
  const loss=e.minus(s).abs(),reward=t.minus(e).abs(),ratio=reward.div(loss);
  out={rr_ratio:str(ratio),breakeven_win_rate:str(loss.div(loss.plus(reward)))};
  if(x.estimated_win_rate!==undefined){const w=dec(x.estimated_win_rate,'estimated_win_rate');if(w.lt(0)||w.gt(1))invalid('Win rate must be between 0 and 1.');out.expectancy_r=str(w.mul(ratio).minus(new Decimal(1).minus(w)));}
 }else if(endpoint==='atr-stop'){
  const e=dec(x.entry_price,'entry_price',true),atr=dec(x.atr_value,'atr_value',true),m=dec(x.multiplier,'multiplier',true);const stop=e.minus(atr.mul(m).mul(direction(x.direction)));if(stop.lte(0))invalid('Calculated stop must be positive.');out={stop_loss_price:str(stop),model:'theoretical_unrounded'};
 }else{
  if(x.instrument_type!=='forex')invalid('Only forex with explicit contract metadata is supported.','unsupported_instrument');
  const c=dec(x.contract_size,'contract_size',true),r=dec(x.quote_to_account_rate,'quote_to_account_rate',true);
  if(typeof x.account_currency!=='string'||!/^[A-Z]{3}$/.test(x.account_currency))invalid('Use a three-letter account_currency.');
  if(typeof x.symbol!=='string'||!/^[A-Z0-9._-]{3,30}$/.test(x.symbol))invalid('Provide a valid symbol.');
  if(endpoint==='position-size'){
   const e=dec(x.entry_price,'entry_price',true),s=dec(x.stop_loss_price,'stop_loss_price',true);if(e.minus(s).mul(direction(x.direction)).lte(0))invalid('Stop must be on the losing side of entry.','invalid_stop_loss');
   if((x.risk_amount===undefined)===(x.risk_percent===undefined))invalid('Provide exactly one risk_amount or risk_percent.');
   const budget=x.risk_amount!==undefined?dec(x.risk_amount,'risk_amount',true):dec(x.account_balance,'account_balance',true).mul(dec(x.risk_percent,'risk_percent',true)).div(100);
   if(x.risk_percent!==undefined&&dec(x.risk_percent,'risk_percent').gt(100))invalid('risk_percent cannot exceed 100.');
   const step=dec(x.lot_step,'lot_step',true),min=dec(x.minimum_lot,'minimum_lot',true),per=e.minus(s).abs().mul(c).mul(r);
   let size=budget.div(per.mul(step)).floor().mul(step);if(size.lt(min))size=new Decimal(0);
   if(size.mul(per).gt(budget))size=size.minus(step); // conservative full-precision verification
   out={position_size:str(size),position_unit:'lots',units:str(size.mul(c)),risk_amount:money(budget),actual_risk_amount:money(size.mul(per)),actual_risk_unrounded:str(size.mul(per)),warnings:size.eq(0)?['position_size_below_minimum']:[]};
  }else if(endpoint==='pip-value')out={pip_value:str(dec(x.pip_size,'pip_size',true).mul(c).mul(dec(x.lot_size,'lot_size',true)).mul(r))};
  else if(endpoint==='margin'){const n=dec(x.lot_size,'lot_size',true).mul(c).mul(dec(x.entry_price,'entry_price',true));out={notional_value:money(n.mul(r)),required_margin:money(n.mul(r).div(dec(x.leverage,'leverage',true))),model:'simple_notional_leverage'};}
  else if(endpoint==='break-even'){
   if(!['spread_included','spread_excluded'].includes(x.entry_basis))invalid('Specify entry_basis as spread_included or spread_excluded.');
   const spread=dec(x.spread_pips,'spread_pips'),commission=dec(x.round_trip_commission_per_lot,'round_trip_commission_per_lot');if(spread.lt(0)||commission.lt(0))invalid('Spread and commission cannot be negative.');
   const offset=(x.entry_basis==='spread_excluded'?spread.mul(dec(x.pip_size,'pip_size',true)):new Decimal(0)).plus(commission.div(c.mul(r)));
   const price=dec(x.entry_price,'entry_price',true).plus(offset.mul(direction(x.direction)));if(price.lte(0))invalid('Break-even price must be positive.');out={break_even_price:str(price)};
  }else invalid('Endpoint not found.','not_found');
  out.account_currency=x.account_currency;out.metadata_basis='caller_supplied';
 }
 return out;
}
function rules(x){
 const out={name:String(x.name||'').trim().slice(0,100),starting_balance:str(dec(x.starting_balance,'starting_balance',true)),daily_loss_percent:str(dec(x.daily_loss_percent,'daily_loss_percent',true)),max_loss_percent:str(dec(x.max_loss_percent,'max_loss_percent',true)),profit_target_percent:str(dec(x.profit_target_percent,'profit_target_percent',true)),max_loss_type:x.max_loss_type,consistency_percent:x.consistency_percent===''||x.consistency_percent==null?null:str(dec(x.consistency_percent,'consistency_percent',true)),min_trading_days:Number(x.min_trading_days),reset_hour_utc:Number(x.reset_hour_utc),breach_on_touch:x.breach_on_touch===true};
 if(!out.name||!['static','trailing','trailing_locked'].includes(out.max_loss_type)||!Number.isInteger(out.min_trading_days)||out.min_trading_days<1||out.min_trading_days>365||!Number.isInteger(out.reset_hour_utc)||out.reset_hour_utc<0||out.reset_hour_utc>23)invalid('Invalid rule set name, type, days or reset hour.');
 for(const k of ['daily_loss_percent','max_loss_percent','profit_target_percent','consistency_percent'])if(out[k]!==null&&new Decimal(out[k]).gt(100))invalid(`${k} cannot exceed 100.`);
 return {...out,version:1,daily_basis:'boundary_balance',account_currency:'USD'};
}
const day=(timestamp,hour)=>new Date(Date.parse(timestamp)-hour*3600000).toISOString().slice(0,10);
function account(r,timestamp): any {return {balance:r.starting_balance,equity:r.starting_balance,hwm:r.starting_balance,daily_start:r.starting_balance,day:day(timestamp,r.reset_hour_utc),daily_profits:{},sequence:0,last_timestamp:timestamp,open_positions:0,status:'active',breach:null,trading_days:[],rule_version:1};}
function event(a,r,x,now=Date.now()){
 if(!Number.isSafeInteger(x.sequence)||x.sequence!==a.sequence+1)invalid('Sequence must be the next account sequence.','event_order_conflict');
 if(typeof x.timestamp!=='string'||!Number.isFinite(Date.parse(x.timestamp))||!/(Z|[+-]\d\d:\d\d)$/.test(x.timestamp)||Date.parse(x.timestamp)<Date.parse(a.last_timestamp)||Date.parse(x.timestamp)>now+60000)invalid('Timestamp must be ordered, timezone-qualified and not in the future.','event_order_conflict');
 if(!['closed_trade','equity_mark','boundary_snapshot'].includes(x.event_type))invalid('Use closed_trade, equity_mark or boundary_snapshot.');
 if(x.event_type!=='closed_trade'&&x.realized_pnl!==undefined&&!dec(x.realized_pnl,'realized_pnl').eq(0))invalid('Only closed_trade may change realized P&L.');
 if(!Number.isInteger(x.open_position_count)||x.open_position_count<0||x.open_position_count>100000)invalid('Provide open_position_count.');
 const delta=x.event_type==='closed_trade'?dec(x.realized_pnl,'realized_pnl'):new Decimal(0),u=dec(x.unrealized_pnl_after,'unrealized_pnl_after');
 if(x.open_position_count===0&&!u.eq(0))invalid('A flat account must have zero unrealized P&L.');
 const next=JSON.parse(JSON.stringify(a)),today=day(x.timestamp,r.reset_hour_utc);
 if(x.event_type==='boundary_snapshot'){
  const boundary=Date.parse(a.day+'T00:00:00Z')+86400000+r.reset_hour_utc*3600000;
  if(Date.parse(x.timestamp)!==boundary)invalid('Boundary snapshot must be at the next reset instant.','boundary_snapshot_required');
  if(x.open_position_count!==a.open_positions)invalid('Boundary snapshot must preserve open position count. Submit closes separately.');
 }else if(today!==a.day&&a.open_positions>0)invalid('Submit a boundary_snapshot at the next reset instant before later events.','boundary_snapshot_required');
 // Check the closing equity against the old daily floor before the reset can lower it.
 const boundaryEquity=new Decimal(a.balance).plus(u),oldDailyFloor=new Decimal(a.daily_start).mul(new Decimal(1).minus(new Decimal(r.daily_loss_percent).div(100)));
 const closingDailyBreach=today!==a.day&&x.event_type==='boundary_snapshot'&&(r.breach_on_touch?boundaryEquity.lte(oldDailyFloor):boundaryEquity.lt(oldDailyFloor));
 if(today!==a.day){next.daily_start=a.balance;next.day=today;}
 const balance=new Decimal(a.balance).plus(delta),equity=balance.plus(u),hwm=Decimal.max(a.hwm,equity),initial=new Decimal(r.starting_balance),maxAmount=initial.mul(r.max_loss_percent).div(100),dailyAmount=new Decimal(next.daily_start).mul(r.daily_loss_percent).div(100);
 if(dailyAmount.lte(0))invalid('Nonpositive boundary balance requires review.');
 const maxFloor=r.max_loss_type==='static'?initial.minus(maxAmount):r.max_loss_type==='trailing_locked'?Decimal.min(hwm.minus(maxAmount),initial):hwm.minus(maxAmount),dailyFloor=new Decimal(next.daily_start).minus(dailyAmount);
 const breached=floor=>r.breach_on_touch?equity.lte(floor):equity.lt(floor);
 const reasons=[];if(breached(dailyFloor)||closingDailyBreach)reasons.push('daily_loss');if(breached(maxFloor))reasons.push('maximum_loss');
 next.balance=str(balance);next.equity=str(equity);next.hwm=str(hwm);next.sequence=x.sequence;next.last_timestamp=x.timestamp;next.open_positions=x.open_position_count;
 if(x.event_type==='closed_trade'){next.daily_profits[today]=str(new Decimal(next.daily_profits[today]||0).plus(delta));if(!next.trading_days.includes(today))next.trading_days.push(today);}
 if(next.trading_days.length>366)invalid('This beta supports at most 366 trading days per phase.');
 const profit=balance.minus(initial),best=Decimal.max(0,...Object.values(next.daily_profits)),share=profit.gt(0)?best.div(profit).mul(100):null,consistent=r.consistency_percent===null||(share!==null&&share.lte(r.consistency_percent));
 next.eligible=!next.breach&&reasons.length===0&&profit.gte(initial.mul(r.profit_target_percent).div(100))&&consistent&&next.trading_days.length>=r.min_trading_days&&next.open_positions===0;
 if(!next.breach&&reasons.length)next.breach={reasons,timestamp:x.timestamp};
 next.status=next.breach?'breached':next.eligible?'eligible':'active';
 next.metrics={daily_floor:str(dailyFloor),daily_remaining:str(equity.minus(dailyFloor)),daily_used_percent:str(Decimal.max(0,new Decimal(next.daily_start).minus(equity)).div(dailyAmount).mul(100)),max_floor:str(maxFloor),max_remaining:str(equity.minus(maxFloor)),max_used_percent:str(Decimal.max(0,new Decimal(1).minus(equity.minus(maxFloor).div(maxAmount))).mul(100)),profit:str(profit),consistency_share_percent:share?str(share):null,consistency_met:consistent,trading_days:next.trading_days.length};
 next.data_basis='submitted_events_only';return next;
}
export {risk,rules,account,event,InputError};
