import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowLeft, BarChart3, Check, Copy, Eye, EyeOff, KeyRound, Radio, Shield, TrendingUp, Wallet } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { useTradingData, computeAnalytics } from "@/hooks/use-trading-data";
import { dataService } from "@/services/database";
import type { Challenge, TradingAccount } from "@/services/types";

const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v||0);
const safeDate=(v?:string)=>v&&Number.isFinite(new Date(v).getTime())?new Date(v).toLocaleDateString():"Pending";
export default function AccountWorkspace(){
  const {challengeId=""}=useParams(),{user}=useAuth(),data=useTradingData(); const [challenge,setChallenge]=useState<Challenge|null>(null),[account,setAccount]=useState<TradingAccount|null>(null),[tab,setTab]=useState("overview"),[show,setShow]=useState(false),[copied,setCopied]=useState("");
  useEffect(()=>{if(!user)return;Promise.all([dataService.getChallenges(user.userId),dataService.getAccounts(user.userId)]).then(([cs,as])=>{const c=cs.find(x=>x.challengeId===challengeId)||null;setChallenge(c);setAccount(c?as.find(x=>x.challengeId===c.challengeId)||null:null)})},[challengeId,user]);
  const trades=useMemo(()=>data.trades.filter(t=>t.challengeId===challengeId||!!account&&(t.accountId===account.accountId||t.accountId===account.login)),[data.trades,challengeId,account]); const a=computeAnalytics(trades);
  const curve=useMemo(()=>{let running=challenge?.accountSize||0;return [{label:"Start",balance:running},...trades.slice().reverse().map((t,i)=>({label:t.closeTime?new Date(t.closeTime).toLocaleDateString(undefined,{month:"short",day:"numeric"}):String(i+1),balance:Number((running+=t.pnl).toFixed(2))}))]},[trades,challenge]);
  const bySymbol=useMemo(()=>Object.entries(trades.reduce<Record<string,number>>((m,t)=>(m[t.symbol]=(m[t.symbol]||0)+t.pnl,m),{})).map(([symbol,pnl])=>({symbol,pnl})),[trades]);
  if(!challenge)return <div className="premium-card py-16 text-center"><p className="font-semibold">Loading account workspace…</p><Link className="mt-3 inline-block text-sm underline" to="/dashboard">Back to overview</Link></div>;
  const copy=async(k:string,v:string)=>{await navigator.clipboard.writeText(v);setCopied(k);setTimeout(()=>setCopied(""),1500)};
  return <div className="space-y-6 animate-fade-up">
    <div><Link to="/dashboard" className="inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft size={14}/>All challenges</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-muted-foreground">Account workspace</p><h1 className="mt-1 text-2xl font-bold">{challenge.name}</h1><p className="mt-1 font-mono text-xs text-muted-foreground">{challenge.challengeId}</p></div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-semibold capitalize">{challenge.status}</span></div></div>
    <div className="flex gap-1 overflow-x-auto rounded-xl border bg-card p-1">{[["overview","Overview",Wallet],["metrix","Account MetriX",TrendingUp],["analysis","Analysis",BarChart3],["credentials","Credentials",KeyRound]].map(([id,label,Icon]:any)=><button key={id} onClick={()=>setTab(id)} className={`inline-flex shrink-0 items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-medium ${tab===id?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-secondary"}`}><Icon size={15}/>{label}</button>)}</div>
    {tab==="overview"&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Balance",money(account?.balance||challenge.accountSize)],["Equity",money(account?.equity||challenge.accountSize)],["Net P/L",money(a?.totalPnl||0)],["Closed trades",trades.length]].map(([x,v])=><div className="premium-card" key={x}><p className="text-xs text-muted-foreground">{x}</p><p className="mt-2 text-2xl font-bold">{v}</p></div>)}</div><div className="grid gap-5 lg:grid-cols-2"><Info challenge={challenge} account={account}/><Status account={account}/></div></>}
    {tab==="metrix"&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Win rate",`${(a?.winRate||0).toFixed(1)}%`],["Profit factor",(a?.profitFactor||0).toFixed(2)],["Avg. R:R",(a?.avgRR||0).toFixed(2)],["Max drawdown",money(a?.maxDrawdown||0)]].map(([x,v])=><div className="premium-card" key={x}><p className="text-xs text-muted-foreground">{x}</p><p className="mt-2 text-2xl font-bold">{v}</p></div>)}</div><Chart title="Balance curve" data={curve} dataKey="balance"/><div className="grid gap-5 lg:grid-cols-2"><Chart title="Results by instrument" data={bySymbol} dataKey="pnl" bar/><Metrics a={a}/></div></>}
    {tab==="analysis"&&<Analysis trades={trades} a={a}/>} 
    {tab==="credentials"&&<div className="premium-card"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Trading platform credentials</h2><p className="mt-1 text-xs text-muted-foreground">Sensitive values remain hidden until you choose to reveal them.</p></div><button disabled={!account} onClick={()=>setShow(!show)} className="inline-flex items-center gap-2 rounded-md border px-3 py-2 text-xs disabled:opacity-40">{show?<EyeOff size={14}/>:<Eye size={14}/>} {show?"Hide":"Reveal"}</button></div>{account?<div className="mt-6 divide-y rounded-lg border">{[["Platform",account.platform],["Server",account.server],["Login",account.login],["Password",account.password]].map(([k,v])=><div className="grid gap-2 p-4 sm:grid-cols-[160px_1fr_auto] sm:items-center" key={k}><span className="text-xs text-muted-foreground">{k}</span><span className="break-all font-mono text-sm">{["Login","Password"].includes(k)&&!show?"••••••••••••":v||"Pending"}</span>{v&&<button aria-label={`Copy ${k}`} onClick={()=>copy(k,v)} className="rounded p-2 hover:bg-secondary">{copied===k?<Check size={14}/>:<Copy size={14}/>}</button>}</div>)}</div>:<div className="mt-8 rounded-xl border border-dashed p-12 text-center"><Shield className="mx-auto text-muted-foreground"/><p className="mt-3 font-semibold">Credentials are being provisioned</p><p className="mt-1 text-sm text-muted-foreground">They will appear here and in your email after the broker creates the account.</p></div>}</div>}
  </div>
}
function Info({challenge:c,account:a}:{challenge:Challenge;account:TradingAccount|null}){return <div className="premium-card"><h2 className="font-semibold">Account information</h2><div className="mt-4 divide-y">{[["Account size",money(c.accountSize)],["Evaluation",c.phase.replace("-"," ")],["Style",c.style],["Started",safeDate(c.startDate)],["Broker account",c.brokerAccountId||a?.login||"Pending"]].map(([k,v])=><div className="flex justify-between py-3 text-sm" key={k}><span className="text-muted-foreground">{k}</span><b className="capitalize">{v}</b></div>)}</div></div>}
function Status({account}:{account:TradingAccount|null}){return <div className="premium-card"><h2 className="font-semibold">Connection & access</h2><div className="mt-5 flex items-start gap-3"><span className="rounded-lg bg-secondary p-2"><Radio size={17}/></span><div><p className="text-sm font-semibold">{account?"Broker account connected":"Awaiting broker provisioning"}</p><p className="mt-1 text-xs text-muted-foreground">{account?"Balance, equity and closed trades are available for real-time synchronization.":"FYNX is ready; credentials and verified market activity begin after broker setup."}</p></div></div></div>}
function Chart({title,data,dataKey,bar=false}:{title:string;data:any[];dataKey:string;bar?:boolean}){return <div className="premium-card"><h2 className="font-semibold">{title}</h2><div className="mt-5 h-72">{data.length>1||bar&&data.length?<ResponsiveContainer width="100%" height="100%">{bar?<BarChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={.2}/><XAxis dataKey="symbol" fontSize={10}/><YAxis fontSize={10}/><Tooltip/><Bar dataKey={dataKey} fill="currentColor" opacity={.75}/></BarChart>:<AreaChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={.2}/><XAxis dataKey="label" fontSize={10}/><YAxis fontSize={10}/><Tooltip/><Area dataKey={dataKey} stroke="currentColor" fill="currentColor" fillOpacity={.12}/></AreaChart>}</ResponsiveContainer>:<div className="flex h-full items-center justify-center rounded-lg border border-dashed text-sm text-muted-foreground">Waiting for broker trade data</div>}</div></div>}
function Metrics({a}:{a:ReturnType<typeof computeAnalytics>}){return <div className="premium-card"><h2 className="font-semibold">General statistics</h2><div className="mt-4 divide-y">{[["Result",money(a?.totalPnl||0)],["Average profit",money(a?.avgWin||0)],["Average loss",money(-(a?.avgLoss||0))],["Expectancy",money(a?.expectancy||0)],["Best instrument",a?.bestPair||"—"],["Best session",a?.bestSession||"—"]].map(([k,v])=><div className="flex justify-between py-3 text-sm" key={k}><span className="text-muted-foreground">{k}</span><b>{v}</b></div>)}</div></div>}
function Analysis({trades,a}:{trades:any[];a:ReturnType<typeof computeAnalytics>}){const longs=trades.filter(t=>t.type==="Buy"),shorts=trades.filter(t=>t.type==="Sell"),sum=(x:any[])=>x.reduce((s,t)=>s+t.pnl,0);return <><div className="premium-card"><h2 className="font-semibold">Automated account analysis</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{trades.length?`This account has ${trades.length} closed trades with a ${(a?.winRate||0).toFixed(1)}% win rate and ${money(a?.totalPnl||0)} net result. Average reward-to-risk is ${(a?.avgRR||0).toFixed(2)} and maximum observed drawdown is ${money(a?.maxDrawdown||0)}. Review the long/short split and instrument results below before changing risk.`:"Analysis will be generated from verified broker trades. No sample results are presented as real account performance."}</p></div><div className="grid gap-5 lg:grid-cols-2"><div className="premium-card"><h3 className="font-semibold">Long / short comparison</h3><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-lg bg-secondary/50 p-4"><p className="text-xs text-muted-foreground">Long</p><b className="mt-2 block text-xl">{longs.length} · {money(sum(longs))}</b></div><div className="rounded-lg bg-secondary/50 p-4"><p className="text-xs text-muted-foreground">Short</p><b className="mt-2 block text-xl">{shorts.length} · {money(sum(shorts))}</b></div></div></div><Metrics a={a}/></div></>}
