import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useTradingData, computeAnalytics } from "@/hooks/use-trading-data";
import { Activity, BarChart3, CalendarDays, Radio } from "lucide-react";
import type { ElementType } from "react";
import { ANALYTICS_RANGES, analyticsRangeLabel, filterByDateRange, type AnalyticsRange } from "@/lib/dateRange";

const money=(v:number)=>`${v>=0?"+":"-"}$${Math.abs(v).toFixed(2)}`;
export default function Analytics(){
  const data=useTradingData(),[range,setRange]=useState<AnalyticsRange>("All");
  const trades=useMemo(()=>filterByDateRange(data.trades,range,t=>t.closeTime),[data.trades,range]);
  const analytics=computeAnalytics(trades);
  const curve=useMemo(()=>{let total=0;return trades.slice().reverse().map((t,i)=>({name:t.closeTime?new Date(t.closeTime).toLocaleDateString(undefined,{month:"short",day:"numeric"}):`Trade ${i+1}`,pnl:Number((total+=t.pnl).toFixed(2))}))},[trades]);
  const stats=["Total trades",analytics?.totalTrades||0,"Net P/L",money(analytics?.totalPnl||0),"Win rate",`${(analytics?.winRate||0).toFixed(1)}%`,"Profit factor",(analytics?.profitFactor||0).toFixed(2),"Expectancy",money(analytics?.expectancy||0),"Max drawdown",`$${(analytics?.maxDrawdown||0).toFixed(2)}`];
  return <div className="space-y-6 animate-fade-up">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight">Analytics</h1><p className="mt-1 text-sm text-muted-foreground">Live performance, risk and behavior insights.</p><p className="mt-1 text-xs text-muted-foreground">{analyticsRangeLabel(range)} · showing {trades.length} of {data.trades.length} closed trades</p></div><div className="flex rounded-lg border p-1" aria-label="Analytics date range">{ANALYTICS_RANGES.map(x=><button type="button" aria-pressed={range===x} onClick={()=>setRange(x)} className={`rounded-md px-3 py-1.5 text-xs ${range===x?"bg-primary text-primary-foreground":"text-muted-foreground"}`} key={x}>{x}</button>)}</div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{Array.from({length:6},(_,i)=><div className="premium-card" key={String(stats[i*2])}><p className="text-xs text-muted-foreground">{stats[i*2]}</p><p className="mt-2 text-xl font-bold">{stats[i*2+1]}</p></div>)}</div>
    <div className="grid gap-5 lg:grid-cols-[2fr_1fr]">
      <div className="premium-card"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Cumulative P/L</h3><p className="text-xs text-muted-foreground">Verified closed trades · {range}</p></div><BarChart3 size={18}/></div><div className="mt-5 h-72">{curve.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={curve}><defs><linearGradient id="pnl" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="currentColor" stopOpacity={.25}/><stop offset="95%" stopColor="currentColor" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" opacity={.25}/><XAxis dataKey="name" fontSize={11}/><YAxis fontSize={11}/><Tooltip/><Area type="monotone" dataKey="pnl" stroke="currentColor" fill="url(#pnl)" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<div className="flex h-full flex-col items-center justify-center rounded-lg border border-dashed"><Activity className="text-muted-foreground"/><p className="mt-3 text-sm font-semibold">Chart ready for live trades</p><p className="mt-1 max-w-sm text-center text-xs text-muted-foreground">Once the broker sends the first closed trade, the equity curve builds automatically. No demo performance is shown.</p></div>}</div></div>
      <div className="premium-card"><h3 className="font-semibold">Data status</h3><div className="mt-5 space-y-4">{([[Radio,data.brokerConnected?"Broker connected":"Awaiting broker",data.brokerConnected?"Listening for verified trade events":"Connect broker API to begin automatic import"],[CalendarDays,`${new Set(trades.map(t=>t.closeTime.slice(0,10))).size} trading days`,`${range} · calculated from closed trades`],[Activity,trades.length?"Analytics live":"No trade history in this range","This workspace stays ready before purchase"]] as Array<[ElementType,string,string]>).map(([Icon,t,d])=><div className="flex gap-3" key={t}><span className="rounded-lg bg-secondary p-2"><Icon size={16}/></span><div><p className="text-sm font-medium">{t}</p><p className="text-xs text-muted-foreground">{d}</p></div></div>)}</div></div>
    </div>
    <div className="grid gap-5 lg:grid-cols-2"><div className="premium-card"><h3 className="font-semibold">Session performance</h3><div className="mt-4 space-y-3">{Object.entries(analytics?.sessions||{London:0,"New York":0,Asia:0}).map(([x,v])=><div className="flex items-center justify-between rounded-lg bg-secondary/50 px-4 py-3" key={x}><span className="text-sm">{x}</span><b>{money(v)}</b></div>)}</div></div><div className="premium-card"><h3 className="font-semibold">Instrument performance</h3><div className="mt-4 space-y-3">{analytics?.instruments.length?analytics.instruments.slice(0,6).map(([x,v])=><div className="flex items-center justify-between rounded-lg bg-secondary/50 px-4 py-3" key={x}><span className="text-sm">{x} <small className="text-muted-foreground">· {v.count} trades</small></span><b>{money(v.pnl)}</b></div>):<p className="rounded-lg bg-secondary/50 p-5 text-sm text-muted-foreground">Pairs will be ranked here after trading begins.</p>}</div></div></div>
  </div>
}
