import { useEffect, useMemo, useState } from "react";
import { Award, BadgeCheck, CalendarCheck, Copy, Download, ExternalLink, FileText, Filter, Share2, ShieldCheck, Sparkles, Trophy, Wallet } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { CERTIFICATE_TYPE_GROUP, getCertificateTitle, getUserCertificates } from "@/services/certificates";
import type { Certificate } from "@/services/types";

type FilterKey = "All" | "Passed" | "Funded" | "Payouts" | "Milestones";
const filters: FilterKey[] = ["All", "Passed", "Funded", "Payouts", "Milestones"];

const icons = {
  challenge_passed: CalendarCheck,
  verification_passed: ShieldCheck,
  funded_trader: Trophy,
  first_payout: Wallet,
  milestone: Sparkles,
  consistency: BadgeCheck,
  top_trader: Trophy,
  scaling_plan: Award,
  profit_split: Wallet,
  account_completion: FileText,
} as const;

function money(value?: number) {
  return typeof value === "number" && value > 0 ? `$${value.toLocaleString()}` : "—";
}

function date(value?: unknown) {
  if (!value) return "—";
  const parsed = typeof value === "object" && value !== null && "toDate" in value ? (value as { toDate: () => Date }).toDate() : new Date(value as string);
  return Number.isNaN(parsed.getTime()) ? "—" : parsed.toLocaleDateString();
}

export default function Certificates() {
  const { user } = useAuth();
  const [activeFilter, setActiveFilter] = useState<FilterKey>("All");
  const [certificates, setCertificates] = useState<Certificate[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!user?.userId) return;
    let mounted = true;
    getUserCertificates(user.userId)
      .then((items) => mounted && setCertificates(items.filter((item) => item.status !== "revoked")))
      .finally(() => mounted && setLoading(false));
    return () => { mounted = false; };
  }, [user?.userId]);

  const filteredCertificates = useMemo(() => certificates.filter((certificate) => activeFilter === "All" || CERTIFICATE_TYPE_GROUP[certificate.type] === activeFilter), [activeFilter, certificates]);

  const counts = useMemo(() => filters.reduce<Record<FilterKey, number>>((acc, key) => {
    acc[key] = key === "All" ? certificates.length : certificates.filter((certificate) => CERTIFICATE_TYPE_GROUP[certificate.type] === key).length;
    return acc;
  }, { All: 0, Passed: 0, Funded: 0, Payouts: 0, Milestones: 0 }), [certificates]);

  return (
    <div className="space-y-8 animate-fade-up">
      <section className="relative overflow-hidden rounded-[2rem] border border-border bg-[radial-gradient(circle_at_top_left,hsl(var(--foreground)/0.16),transparent_34%),linear-gradient(135deg,hsl(var(--background)),hsl(var(--secondary)/0.55))] p-6 shadow-2xl sm:p-8">
        <div className="absolute right-6 top-6 hidden h-28 w-28 rounded-full border border-foreground/10 sm:block" />
        <div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 rounded-full border border-border bg-background/70 px-3 py-1 text-xs uppercase tracking-[0.25em] text-muted-foreground">
              <Award size={14} /> FYNX Funded Certificates
            </div>
            <h1 className="mt-5 text-3xl font-semibold tracking-tight sm:text-5xl">Verified trader achievements, unlocked from real account progress.</h1>
            <p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground sm:text-base">Challenge, verification, funded, payout, milestone, consistency, top trader, scaling, profit split, and completion certificates are generated by backend account, objective, trade, payout, and status events—not by this page.</p>
          </div>
          <div className="grid grid-cols-3 gap-3 rounded-2xl border border-border bg-background/70 p-3 text-center backdrop-blur">
            <Stat label="Issued" value={certificates.length} />
            <Stat label="Funded" value={counts.Funded} />
            <Stat label="Payouts" value={counts.Payouts} />
          </div>
        </div>
      </section>

      <div className="flex flex-wrap items-center gap-2">
        <span className="inline-flex items-center gap-2 text-sm text-muted-foreground"><Filter size={15} /> Filter</span>
        {filters.map((filter) => (
          <button key={filter} onClick={() => setActiveFilter(filter)} className={`rounded-full border px-4 py-2 text-sm transition ${activeFilter === filter ? "border-foreground bg-foreground text-background" : "border-border bg-secondary/60 text-muted-foreground hover:text-foreground"}`}>
            {filter} <span className="ml-1 opacity-60">{counts[filter]}</span>
          </button>
        ))}
      </div>

      {loading ? (
        <div className="premium-card grid min-h-[320px] place-items-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-muted-foreground/30 border-t-foreground" /></div>
      ) : filteredCertificates.length > 0 ? (
        <div className="grid gap-6 xl:grid-cols-2">
          {filteredCertificates.map((certificate) => <CertificateCard key={certificate.certificateId} certificate={certificate} />)}
        </div>
      ) : (
        <EmptyCertificateState />
      )}
    </div>
  );
}

function CertificateCard({ certificate }: { certificate: Certificate }) {
  const Icon = icons[certificate.type] || Award;
  const verifyHref = certificate.verificationUrl || `/certificates/verify/${certificate.publicVerificationId}`;

  const handleCopy = async () => navigator.clipboard?.writeText(verifyHref);
  const handleShare = async () => {
    if (navigator.share) await navigator.share({ title: getCertificateTitle(certificate.type), text: "Verified FYNX Funded certificate", url: verifyHref });
    else await handleCopy();
  };
  const handleDownload = () => window.print();

  return (
    <article className="group overflow-hidden rounded-[1.75rem] border border-border bg-card shadow-xl">
      <div className="relative border-b border-border bg-black p-6 text-white sm:p-8 print:bg-white print:text-black">
        <div className="absolute inset-0 opacity-40 [background:radial-gradient(circle_at_20%_10%,white,transparent_18%),linear-gradient(135deg,transparent,rgba(255,255,255,.14))]" />
        <div className="relative flex items-start justify-between gap-4">
          <div>
            <p className="text-xs uppercase tracking-[0.35em] text-white/55 print:text-black/50">FYNX Funded</p>
            <h2 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">{getCertificateTitle(certificate.type)}</h2>
          </div>
          <div className="grid h-14 w-14 place-items-center rounded-2xl border border-white/20 bg-white/10"><Icon size={28} /></div>
        </div>
        <div className="relative mt-10 rounded-2xl border border-white/15 bg-white/[0.06] p-5 print:border-black/20">
          <p className="text-sm text-white/55 print:text-black/50">Awarded to</p>
          <p className="mt-1 text-3xl font-semibold">{certificate.traderName}</p>
          <p className="mt-4 text-sm leading-6 text-white/60 print:text-black/60">For verified progress on {certificate.challengeType} with account {certificate.accountId}.</p>
        </div>
      </div>

      <div className="space-y-5 p-6 sm:p-8">
        <div className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-3">
          <Info label="Account ID" value={certificate.accountId} />
          <Info label="Challenge" value={certificate.challengeType} />
          <Info label="Account Size" value={money(certificate.accountSize)} />
          <Info label="Passed" value={date(certificate.passedDate)} />
          <Info label="Funded" value={date(certificate.fundedDate)} />
          <Info label="Profit Split" value={certificate.profitSplit || "—"} />
        </div>

        {certificate.rulesSnapshot && (
          <div className="rounded-2xl border border-border bg-secondary/30 p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-muted-foreground">Objectives snapshot</p>
            <div className="mt-3 grid grid-cols-2 gap-3 text-sm sm:grid-cols-5">
              <Info label="Target" value={certificate.rulesSnapshot.profitTargets.join(" / ")} />
              <Info label="Daily Loss" value={certificate.rulesSnapshot.dailyLoss} />
              <Info label="Max Loss" value={certificate.rulesSnapshot.maxLoss} />
              <Info label="Min Days" value={String(certificate.rulesSnapshot.minDays)} />
              <Info label="Split" value={certificate.rulesSnapshot.profitSplit} />
            </div>
          </div>
        )}

        <div className="flex flex-col gap-3 rounded-2xl border border-border p-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Certificate ID</p>
            <p className="mt-1 break-all font-mono text-sm font-semibold">{certificate.publicVerificationId}</p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Link to={`/certificates/verify/${certificate.publicVerificationId}`} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm hover:bg-secondary"><ExternalLink size={14} /> Verify</Link>
            <button onClick={handleDownload} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm hover:bg-secondary"><Download size={14} /> PDF</button>
            <button onClick={handleShare} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm hover:bg-secondary"><Share2 size={14} /> Share</button>
            <button onClick={handleCopy} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm hover:bg-secondary"><Copy size={14} /> Copy</button>
          </div>
        </div>
      </div>
    </article>
  );
}

function EmptyCertificateState() {
  return (
    <div className="relative overflow-hidden rounded-[2rem] border border-border bg-[linear-gradient(135deg,hsl(var(--secondary)/0.55),hsl(var(--background)))] p-8 text-center shadow-xl sm:py-16">
      <div className="mx-auto grid h-20 w-20 place-items-center rounded-full border border-border bg-background shadow-inner"><Award size={36} /></div>
      <h3 className="mt-6 text-2xl font-semibold">Your certificate vault is ready</h3>
      <p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted-foreground">No certificates are unlocked yet. They will appear automatically only after backend records confirm phase passes, funded status, paid payouts, or eligible milestone events.</p>
      <div className="mx-auto mt-8 grid max-w-3xl gap-3 text-left sm:grid-cols-3">
        <EmptyStep title="Pass Phase 1" text="Unlock Challenge Passed from account status and objectives." />
        <EmptyStep title="Complete Verification" text="Unlock Verification Passed when Phase 2 records are complete." />
        <EmptyStep title="Get Funded & Paid" text="Unlock funded, payout, split, and scaling certificates from real events." />
      </div>
    </div>
  );
}

function EmptyStep({ title, text }: { title: string; text: string }) {
  return <div className="rounded-2xl border border-border bg-background/70 p-4"><p className="font-medium">{title}</p><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>;
}

function Stat({ label, value }: { label: string; value: number }) {
  return <div className="min-w-20"><p className="text-2xl font-semibold">{value}</p><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">{label}</p></div>;
}

function Info({ label, value }: { label: string; value: string }) {
  return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>;
}
