// @ts-nocheck
// GENERATED by FYNX API scripts/proof/sync-funded-policy.cjs. Do not edit.
'use strict';
// One versioned Funded policy evaluated by the API's canonical event engine.
// This is opt-in: never infer the purchased contract from today's public page.
import * as engine from './apiRuleEngine';
const VERSION='fynx-funded-v1';
const PROGRAMS=Object.freeze({'1-phase':{targets:[10],daily:4,max:8,days:3},'2-phase':{targets:[8,5],daily:5,max:10,days:5},'3-phase':{targets:[6,5,4],daily:5,max:12,days:5}});
const canonical=x=>JSON.stringify(x===null||typeof x!=='object'?x:Array.isArray(x)?x.map(v=>JSON.parse(canonical(v))):Object.fromEntries(Object.keys(x).sort().map(k=>[k,JSON.parse(canonical(x[k]))])));
function fail(message){throw new engine.InputError(message,'policy_review_required');}
function timestamp(value){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value.slice(0,10)+'T00:00:00Z').toISOString().slice(0,10)===value.slice(0,10);}
function ruleSnapshot({program,phase,starting_balance,currency}){
 const p=PROGRAMS[program];
 if(!p||!Number.isInteger(phase)||phase<1||phase>p.targets.length||currency!=='USD')fail('Verified USD program and phase are required.');
 if(!['5000','10000','25000','50000','100000','200000'].includes(starting_balance))fail('Unsupported Funded starting balance.');
 return engine.rules({name:VERSION+':'+program+':'+phase,starting_balance,daily_loss_percent:String(p.daily),max_loss_percent:String(p.max),profit_target_percent:String(p.targets[phase-1]),max_loss_type:'static',consistency_percent:'40',min_trading_days:p.days,reset_hour_utc:22,breach_on_touch:false});
}
function validateBinding(context){
 if(!context||context.policy_version!==VERSION)fail('An explicit supported policy version is required; legacy agreements are not migrated automatically.');
 const rule=ruleSnapshot(context),a=context.agreement;
 if(!a||a.verified!==true||typeof a.reference!=='string'||!a.reference.trim()||!/^([a-f0-9]{64})$/.test(a.document_sha256||'')||!timestamp(a.accepted_at)||!timestamp(a.reviewed_at)||typeof a.reviewed_by!=='string'||!a.reviewed_by.trim())fail('Reviewed purchased-agreement evidence is required.');
 if(Date.parse(a.reviewed_at)>Date.now())fail('Agreement review cannot be in the future.');
 if(Date.parse(a.reviewed_at)<Date.parse(a.accepted_at))fail('Agreement review cannot predate acceptance.');
 if(a.policy_version!==VERSION||canonical(a.rule_snapshot)!==canonical(rule))fail('Purchased rule snapshot does not match this policy; preserve the original agreement and review separately.');
 if(!timestamp(context.start_timestamp)||Date.parse(context.start_timestamp)<Date.parse(a.accepted_at))fail('Phase start must be timezone-qualified and not precede acceptance.');
 return rule;
}
// A review attestation is required in addition to structural checks; it is not created here.
function validateCoverage(context,events){
 const c=context.coverage;
 if(!c||c.complete!==true||c.pagination_complete!==true||c.equity_complete!==true||!c.source_reference||!c.adapter_version||!c.reviewed_by||!timestamp(c.reviewed_at)||Date.parse(c.reviewed_at)>Date.now()||!/^([a-f0-9]{64})$/.test(c.source_sha256||''))fail('Reviewed complete broker export, equity coverage and adapter version are required.');
 if(c.from!==context.start_timestamp||c.through!==events.at(-1)?.timestamp||c.event_count!==events.length||!Number.isSafeInteger(c.source_sequence_start)||c.source_sequence_start<0||c.source_sequence_end!==c.source_sequence_start+events.length-1)fail('Coverage interval, event count or source watermark does not match history.');
 if(typeof c.account_id!=='string'||!c.account_id.trim()||c.phase_reference!==context.agreement.reference+':phase:'+context.phase)fail('Coverage must identify the broker account and exact purchased phase.');
 for(const [i,e] of events.entries()){
  if(e.account_id!==c.account_id||e.phase_reference!==c.phase_reference||e.source_sequence!==c.source_sequence_start+i)fail('Mixed-account, mixed-phase or gapped source history.');
  if(e.event_type==='closed_trade'&&e.pnl_basis!=='net_after_all_costs')fail('Closed events require explicit net-after-all-costs mapping.');
 }
}
function decimalText(value){
 if(typeof value!=='string'||!/^[-+]?\d{1,18}(\.\d{1,12})?$/.test(value))fail('Independent broker balance and equity decimal strings are required.');
 const negative=value[0]==='-',parts=value.replace(/^[-+]/,'').split('.');
 const whole=parts[0].replace(/^0+(?=\d)/,''),fraction=(parts[1]||'').replace(/0+$/,'');
 const number=whole+(fraction?'.'+fraction:'');return negative&&number!=='0'?'-'+number:number;
}
function evaluate(context,events){
 const rule=validateBinding(context);
 if(!Array.isArray(events)||!events.length)fail('Complete ordered equity-event history is required.');
 validateCoverage(context,events);
 const identities=new Set();let state=engine.account(rule,context.start_timestamp);
 for(const e of events){
  if(typeof e.source_event_id!=='string'||!e.source_event_id.trim()||identities.has(e.source_event_id))fail('Each broker event must have a unique source identity.');
  if(!timestamp(e.timestamp))fail('Invalid event calendar date or timezone.');
  identities.add(e.source_event_id);state=engine.event(state,rule,e);
  if(decimalText(e.broker_balance)!==decimalText(state.balance)||decimalText(e.broker_equity)!==decimalText(state.equity))fail('Broker balance/equity does not reconcile with net event history.');
 }
 if(context.recorded_breach){
  if(!Array.isArray(context.recorded_breach.reasons)||!context.recorded_breach.reasons.length||!timestamp(context.recorded_breach.timestamp))fail('Invalid persisted breach evidence.');
  state.breach=context.recorded_breach;state.eligible=false;state.status='breached';
 }
 return {policy_version:VERSION,rule,state,requires_human_review:true,authorizes_phase_transition:false,agreement_reference:context.agreement.reference};
}
export {VERSION,ruleSnapshot,validateBinding,evaluate};
