// @ts-nocheck
// GENERATED by FYNX API scripts/proof/sync-funded-policy.cjs. Do not edit.
'use strict';
import {createHash} from 'crypto';
import * as policy from './fundedPolicy';
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
function build({uid,program,starting_balance,accepted_version,accepted,now=new Date().toISOString()}){
 if(typeof uid!=='string'||!uid||accepted!==true||accepted_version!==policy.VERSION)throw Error('Explicit acceptance of the current numerical rules is required.');
 if(!Number.isFinite(Date.parse(now)))throw Error('Invalid acceptance time.');
 const phases={'1-phase':1,'2-phase':2,'3-phase':3}[program];if(!phases)throw Error('Invalid program.');
 const document={policy_version:policy.VERSION,program,starting_balance,currency:'USD',phases:Array.from({length:phases},(_,i)=>policy.ruleSnapshot({program,phase:i+1,starting_balance,currency:'USD'}))};
 return {uid,document,document_sha256:hash(document),accepted_at:now,acceptance_source:'authenticated_checkout',scope:'numerical_rules_only'};
}
function bind(purchase,{uid,order_id,program,starting_balance,start_timestamp,expected_hash}){
 if(!purchase||purchase.uid!==uid||purchase.acceptance_source!=='authenticated_checkout'||purchase.scope!=='numerical_rules_only'||purchase.document_sha256!==hash(purchase.document)||purchase.document_sha256!==expected_hash)throw Error('Missing or mismatched recorded purchased rules. Do not infer past acceptance.');
 const d=purchase.document;
 const expected=build({uid,program,starting_balance,accepted_version:policy.VERSION,accepted:true,now:purchase.accepted_at}).document;
 if(JSON.stringify(d)!==JSON.stringify(expected))throw Error('Purchased rules do not match this supported version; review the original agreement.');
 const context={policy_version:policy.VERSION,program,phase:1,starting_balance,currency:'USD',start_timestamp,agreement:{verified:true,reference:'order:'+order_id,document_sha256:purchase.document_sha256,accepted_at:purchase.accepted_at,reviewed_at:purchase.accepted_at,reviewed_by:'authenticated-checkout-snapshot-verifier',policy_version:policy.VERSION,rule_snapshot:d.phases[0]},coverage:null};
 policy.validateBinding(context);return context;
}
export {build,bind};
